import os


rule all:
    input:
        tsv=expand(
            "results/mash/{genome_fasta}.s{mash_s}.k{mash_k}.s{mash_s}.tsv",
            genome_fasta=config["inphared_genomes"],
            mash_k=config["mash"]["sketch"]["k"],
            mash_s=config["mash"]["sketch"]["s"],
            mash_d=config["mash"]["dist"]["d"],
        ),


# TODO: use inphared download wrapper once available, for progress see:
#       https://github.com/snakemake/snakemake-wrappers/pull/1550
rule download:
    output:
        "resources/{genome_fasta}.fa",
    shell:
        """
        curl -O https://millardlab-inphared.s3.climb.ac.uk/{wildcards.genome_fasta}.fa.gz;
        gunzip {wildcards.genome_fasta}.fa.gz;
        mv {wildcards.genome_fasta}.fa {output[0]}
        """


rule mash_sketch:
    input:
        "resources/{genome_fasta}.fa",
    output:
        msh="results/mash/{genome_fasta}.k{mash_k}.s{mash_s}.fa.msh",
    params:
        prefix=lambda wc, output: os.path.splitext(output.msh)[0],
    conda:
        "envs/mash.yaml"
    threads: 6
    shell:
        """
        mash sketch -i -k {wildcards.mash_k} -s {wildcards.mash_s} -p {threads} -o {params.prefix} {input[0]}
        """


rule mash_dist:
    input:
        msh="results/mash/{genome_fasta}.k{mash_k}.s{mash_s}.fa.msh",
    output:
        tsv="results/mash/{genome_fasta}.k{mash_k}.s{mash_s}.d{mash_d}.tsv",
    conda:
        "envs/mash.yaml"
    threads: 6
    shell:
        """
        mash dist -i -d {wildcards.mash_d} -p {threads} {input.msh} {input.msh} \
        > {output.tsv}
        """
